### ISSUE TITLE
Invalid packet checksum

### ISSUE THREAD

**Issue by gioiann** [Sandertv/gophertunnel#2] opened 2019-06-24 11:09 UTC
I've been getting this error really often, expecially on mineplex. When this happens a temporary "fix" is restarting the proxy but eventually it will happen again.
```
error reading from client connection: error reading batch: invalid packet checksum: d6f4aaa48ed69500 should be 228fc984d0749b49
```
This error message can be either from listener.go or dial.go since it's the same for  both. I found out it's from [there](https://github.com/Sandertv/gophertunnel/blob/master/minecraft/dial.go#L147)

So either the server is not encrypting properly (and i don't think so since it works without proxy) or the proxy is doing something wrong.

**Comment by Sandertv** [comment] 2019-06-24 19:28
This might be fixed on the latest commit thanks to the RakNet changes. Please try it and let me know.

**Comment by gioiann** [comment] 2019-06-25 00:52
The problem is still there, it just happened again. Also, I don't think the last changes to RakNet affect encryption at all. Packets order affects encryption and that has nothing to do with the latest RakNet changes.

**Comment by Sandertv** [comment] 2019-06-25 06:03
I figured if something was wrong with resending, it could affect this. I also am unable to reproduce it. Do you have a high latency to the server?

**Comment by gioiann** [comment] 2019-06-25 14:24
There is no way to reproduce it, just randomly happens. I made more tests and only happened once on lbsg when I had a delay of about 450ms (450/3 = 150ms ACK average RTT)
But during the tests the delay ranged from 200 to even 500ms at some point and everything was just fine.

By delay i mean the `recoveryQueue.AvgDelay * 3`

**Comment by Sandertv** [comment] 2019-09-06 08:21
How frequently does this happen at this time?

**Comment by gioiann** [comment] 2019-09-06 15:10
It isn't happening anymore. I guess it's fixed but I'm not sure as there wasn't a way to reproduce it. I think you can close this issue for now

**Comment by Sandertv** [comment] 2019-09-06 15:11
Alright, thank you. Please do let me know if it happens again!

**Closed by Sandertv** 2019-09-06 15:11 UTC
Labels: bug
