### ISSUE TITLE
Client crashes when opening the chat on a BDS server

### ISSUE THREAD

**Issue by IvanCraft623** [Sandertv/gophertunnel#189] opened 2023-06-10 15:14 UTC

**Comment by alvin0319** [comment] 2023-06-13 10:22
This is actually caused by `block-network-ids-are-hashes` in server.properties. Disabling it will prevent a client from crashing.

**Comment by Sandertv** [comment] 2023-07-22 14:46
This should be fixed in the latest versions.

**Closed by Sandertv** 2023-07-22 14:46 UTC
Labels: bug
